account_app/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from account_app.views import romeo, AccountCreateView, AccountDetailView

app_name = "account_app"

urlpatterns = [
    path('romeo/', romeo, name='romeo'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('login/', LoginView.as_view(template_name='account_app/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
]

pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include("account_app.urls")),
]

account_app/models.py
from django.db import models

# Create your models here.


class Romeo(models.Model):
    text = models.CharField(max_length=255, null=False)

account_app/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView

from account_app.models import Romeo


def romeo(request):

    if request.method == "POST":

        temp = request.POST.get('romeo_input')

        new_romeo = Romeo()
        new_romeo.text = temp
        new_romeo.save()

        return HttpResponseRedirect(reverse('account_app:romeo'))
    else:
        romeo_list = Romeo.objects.all()
        return render(request, 'account_app/romeo.html',
                      context={'romeo_list': romeo_list})


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('account_app:romeo')
    template_name = 'account_app/create.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'account_app/detail.html'

account_app/templates/account_app/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div class="mb-4">
            <h4>Sign Up</h4>
        </div>
        <form action="{% url 'account_app:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-3 mt-3">
        </form>
    </div>
{% endblock %}

account_app/templates/account_app/detail.html
{% extends 'base.html' %}


{% block content %}

    <div>
        <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
            <p>
                {{ target_user.date_joined }}
            </p>
            <h2 style="font-family: 'NanumSquareOTFRegular';">
                {{ target_user.username }}
            </h2>
        </div>
    </div>

{% endblock %}

account_app/templates/account_app/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div>
            <h4>Login</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-3 mt-3">
            </form>
        </div>
    </div>
{% endblock %}

account_app/templates/account_app/romeo.html
{% extends 'base.html' %}

{% block content %}

    <div style="border-radius: 1rem; margin: 2rem; text-align: center;">
        <h1 style="font-family: 'Lobster', cursive;">
            romeo
        </h1>

        <form action="/account/romeo/" method="post">
            {% csrf_token %}
            <div>
                <input type="text" name="romeo_input">
            </div>
            <div>
                <input type="submit" class="btn btn-primary" value="POST">
            </div>

        </form>

        {% if romeo_list %}
            {% for romeo in romeo_list %}
            <h4>
                {{ romeo.text }}
            </h4>
            {% endfor %}
        {% endif %}

    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family: 'NanumSquareOTFLight';">

    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}

</body>
</html>

templates/footer.html
    <div class="pragmatic_footer">
        <div class="pragmatic_footer_button">
            <span>공지사항</span> |
            <span>제휴문의</span> |
            <span>서비스 소개</span>
        </div>
        <div style="margin-top: 1rem;">
            <h6 class="pragmatic_logo">Pragmatic</h6>
        </div>
    </div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Pragmatic</title>

    <!--  bootstrap link  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <!--  google fonts link  -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">

    <!--  default css link  -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <style>
        @font-face {
            font-family: 'NanumSquareOTFBold';
            src: local('NanumSquareOTFBold');
            url("{% static 'fonts/NanumSquareOTFBold.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareOTFExtraBold';
            src: local('NanumSquareOTFExtraBold');
            url("{% static 'fonts/NanumSquareOTFExtraBold.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareOTFLight';
            src: local('NanumSquareOTFLight');
            url("{% static 'fonts/NanumSquareOTFLight.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareOTFRegular';
            src: local('NanumSquareOTFRegular');
            url("{% static 'fonts/NanumSquareOTFRegular.otf' %}") format("opentype");
        }
    </style>

</head>

templates/header.html
    <div class="pragmatic_header">
        <div>
            <h1 class="pragmatic_logo">Pragmatic</h1>
        </div>
        <div>
            <span>nav1</span>
            <span>nav2</span>
            <span>nav3</span>
            {% if not user.is_authenticated %}
            <a href="{% url 'account_app:login' %}?next={{ request.path }}">
                <span>login</span>
            </a>
            {% else %}
            <a href="{% url 'account_app:detail' pk=user.pk %}">
                <span>My Page</span>
            </a>
            <a href="{% url 'account_app:logout' %}?next={{ request.path }}">
                <span>logout</span>
            </a>
            {% endif %}
        </div>
    </div>